-- 1. 문자열 자르기 : SUBSTRING
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) CATEGORY, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY 1;

-- 2. 문자열 자르기 : LEFT
SELECT LEFT(PRODUCT_CODE, 2) CATEGORY, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY 1;